version: "3"

services:
  notificationservice:
    build:
      context: ./
      dockerfile: dockerfile.dev
    container_name: packageservice-dev
    environment:
      CASSANDRA_NODES: '["cassandra1", "cassandra2"]'
      CASSANDRA_LOCAL_DATACENTER: "Denmark"
      CASSANDRA_KEYSPACE: "PackageService"
      PACKAGE_SERVICE_PORT: 6000
    ports:
      - 6000:6000
    volumes:
      - ./src:/opt/app/src/ # for dev purposes
